/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ChatRouteImport } from './routes/_chat'
import { Route as ChatIndexRouteImport } from './routes/_chat.index'
import { Route as ChatSettingsRouteImport } from './routes/_chat.settings'
import { Route as ChatPluginsRouteImport } from './routes/_chat.plugins'
import { Route as ChatAutomationsRouteImport } from './routes/_chat.automations'
import { Route as ChatThreadIdRouteImport } from './routes/_chat.$threadId'
import { Route as ChatWorkspaceIndexRouteImport } from './routes/_chat.workspace.index'
import { Route as ChatAutomationsIndexRouteImport } from './routes/_chat.automations.index'
import { Route as ChatWorkspaceWorkspaceIdRouteImport } from './routes/_chat.workspace.$workspaceId'
import { Route as ChatAutomationsAutomationIdRouteImport } from './routes/_chat.automations.$automationId'

const ChatRoute = ChatRouteImport.update({
  id: '/_chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)
const ChatSettingsRoute = ChatSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ChatRoute,
} as any)
const ChatPluginsRoute = ChatPluginsRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => ChatRoute,
} as any)
const ChatAutomationsRoute = ChatAutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => ChatRoute,
} as any)
const ChatThreadIdRoute = ChatThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => ChatRoute,
} as any)
const ChatWorkspaceIndexRoute = ChatWorkspaceIndexRouteImport.update({
  id: '/workspace/',
  path: '/workspace/',
  getParentRoute: () => ChatRoute,
} as any)
const ChatAutomationsIndexRoute = ChatAutomationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatAutomationsRoute,
} as any)
const ChatWorkspaceWorkspaceIdRoute =
  ChatWorkspaceWorkspaceIdRouteImport.update({
    id: '/workspace/$workspaceId',
    path: '/workspace/$workspaceId',
    getParentRoute: () => ChatRoute,
  } as any)
const ChatAutomationsAutomationIdRoute =
  ChatAutomationsAutomationIdRouteImport.update({
    id: '/$automationId',
    path: '/$automationId',
    getParentRoute: () => ChatAutomationsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ChatIndexRoute
  '/$threadId': typeof ChatThreadIdRoute
  '/automations': typeof ChatAutomationsRouteWithChildren
  '/plugins': typeof ChatPluginsRoute
  '/settings': typeof ChatSettingsRoute
  '/automations/$automationId': typeof ChatAutomationsAutomationIdRoute
  '/workspace/$workspaceId': typeof ChatWorkspaceWorkspaceIdRoute
  '/automations/': typeof ChatAutomationsIndexRoute
  '/workspace/': typeof ChatWorkspaceIndexRoute
}
export interface FileRoutesByTo {
  '/$threadId': typeof ChatThreadIdRoute
  '/plugins': typeof ChatPluginsRoute
  '/settings': typeof ChatSettingsRoute
  '/': typeof ChatIndexRoute
  '/automations/$automationId': typeof ChatAutomationsAutomationIdRoute
  '/workspace/$workspaceId': typeof ChatWorkspaceWorkspaceIdRoute
  '/automations': typeof ChatAutomationsIndexRoute
  '/workspace': typeof ChatWorkspaceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_chat': typeof ChatRouteWithChildren
  '/_chat/$threadId': typeof ChatThreadIdRoute
  '/_chat/automations': typeof ChatAutomationsRouteWithChildren
  '/_chat/plugins': typeof ChatPluginsRoute
  '/_chat/settings': typeof ChatSettingsRoute
  '/_chat/': typeof ChatIndexRoute
  '/_chat/automations/$automationId': typeof ChatAutomationsAutomationIdRoute
  '/_chat/workspace/$workspaceId': typeof ChatWorkspaceWorkspaceIdRoute
  '/_chat/automations/': typeof ChatAutomationsIndexRoute
  '/_chat/workspace/': typeof ChatWorkspaceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$threadId'
    | '/automations'
    | '/plugins'
    | '/settings'
    | '/automations/$automationId'
    | '/workspace/$workspaceId'
    | '/automations/'
    | '/workspace/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$threadId'
    | '/plugins'
    | '/settings'
    | '/'
    | '/automations/$automationId'
    | '/workspace/$workspaceId'
    | '/automations'
    | '/workspace'
  id:
    | '__root__'
    | '/_chat'
    | '/_chat/$threadId'
    | '/_chat/automations'
    | '/_chat/plugins'
    | '/_chat/settings'
    | '/_chat/'
    | '/_chat/automations/$automationId'
    | '/_chat/workspace/$workspaceId'
    | '/_chat/automations/'
    | '/_chat/workspace/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ChatRoute: typeof ChatRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_chat': {
      id: '/_chat'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat/': {
      id: '/_chat/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/settings': {
      id: '/_chat/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ChatSettingsRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/plugins': {
      id: '/_chat/plugins'
      path: '/plugins'
      fullPath: '/plugins'
      preLoaderRoute: typeof ChatPluginsRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/automations': {
      id: '/_chat/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof ChatAutomationsRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/$threadId': {
      id: '/_chat/$threadId'
      path: '/$threadId'
      fullPath: '/$threadId'
      preLoaderRoute: typeof ChatThreadIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/workspace/': {
      id: '/_chat/workspace/'
      path: '/workspace'
      fullPath: '/workspace/'
      preLoaderRoute: typeof ChatWorkspaceIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/automations/': {
      id: '/_chat/automations/'
      path: '/'
      fullPath: '/automations/'
      preLoaderRoute: typeof ChatAutomationsIndexRouteImport
      parentRoute: typeof ChatAutomationsRoute
    }
    '/_chat/workspace/$workspaceId': {
      id: '/_chat/workspace/$workspaceId'
      path: '/workspace/$workspaceId'
      fullPath: '/workspace/$workspaceId'
      preLoaderRoute: typeof ChatWorkspaceWorkspaceIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/automations/$automationId': {
      id: '/_chat/automations/$automationId'
      path: '/$automationId'
      fullPath: '/automations/$automationId'
      preLoaderRoute: typeof ChatAutomationsAutomationIdRouteImport
      parentRoute: typeof ChatAutomationsRoute
    }
  }
}

interface ChatAutomationsRouteChildren {
  ChatAutomationsAutomationIdRoute: typeof ChatAutomationsAutomationIdRoute
  ChatAutomationsIndexRoute: typeof ChatAutomationsIndexRoute
}

const ChatAutomationsRouteChildren: ChatAutomationsRouteChildren = {
  ChatAutomationsAutomationIdRoute: ChatAutomationsAutomationIdRoute,
  ChatAutomationsIndexRoute: ChatAutomationsIndexRoute,
}

const ChatAutomationsRouteWithChildren = ChatAutomationsRoute._addFileChildren(
  ChatAutomationsRouteChildren,
)

interface ChatRouteChildren {
  ChatThreadIdRoute: typeof ChatThreadIdRoute
  ChatAutomationsRoute: typeof ChatAutomationsRouteWithChildren
  ChatPluginsRoute: typeof ChatPluginsRoute
  ChatSettingsRoute: typeof ChatSettingsRoute
  ChatIndexRoute: typeof ChatIndexRoute
  ChatWorkspaceWorkspaceIdRoute: typeof ChatWorkspaceWorkspaceIdRoute
  ChatWorkspaceIndexRoute: typeof ChatWorkspaceIndexRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatThreadIdRoute: ChatThreadIdRoute,
  ChatAutomationsRoute: ChatAutomationsRouteWithChildren,
  ChatPluginsRoute: ChatPluginsRoute,
  ChatSettingsRoute: ChatSettingsRoute,
  ChatIndexRoute: ChatIndexRoute,
  ChatWorkspaceWorkspaceIdRoute: ChatWorkspaceWorkspaceIdRoute,
  ChatWorkspaceIndexRoute: ChatWorkspaceIndexRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ChatRoute: ChatRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
