// FILE: browserUseSkill.ts
// Purpose: Materializes the portable `fcode-browser` skill into `{base}/skills` so every
//   provider CLI (Codex, Claude, Cursor, Gemini, ...) can drive the in-app browser by
//   shelling out to the bundled CLI, which calls the server's browser-use HTTP route.
// Layer: Server browser-use bridge
// Depends on: browser-use HTTP route contract and the skills catalog folder layout

import * as fs from "node:fs/promises";
import * as nodePath from "node:path";

import { readBrowserUsePipePathFromEnv } from "@t3tools/shared/browserUsePipe";

import { fcodeSkillsDir } from "../provider/skillsCatalog.ts";
import { BROWSER_USE_HTTP_ROUTE_PATH } from "./browserUseHttpRoute.ts";

export const BROWSER_USE_SKILL_NAME = "fcode-browser";

interface BrowserUseSkillRuntimeConfig {
  serverUrl: string;
  token: string | null;
  routePath: string;
}

function buildSkillMarkdown(skillDir: string): string {
  const cli = `node "${nodePath.join(skillDir, "browser.mjs")}"`;
  return `---
name: ${BROWSER_USE_SKILL_NAME}
description: Control FCode's built-in in-app browser — open URLs, inspect pages as indexed interactive elements, click, fill forms, take screenshots, and read the page console. Use whenever a task needs to browse the web, test a web page, or verify a local dev server inside the FCode app.
---

# FCode in-app browser

FCode embeds a browser panel that the user can watch live. Control it by running:

\`\`\`
${cli} <command> [args...]
\`\`\`

## Commands

| Command | Description |
| --- | --- |
| \`tabs\` | List open tabs |
| \`navigate <url>\` | Open a URL and wait for load |
| \`page-state\` | Page as indexed interactive elements, e.g. \`[4]<a role=button>Sign in />\` |
| \`click-element <index>\` | Click an element by its [index] from page-state |
| \`input-text <index> <text...>\` | Focus a field by [index] and replace its text |
| \`select-option <index> <text...>\` | Pick a dropdown option by visible text |
| \`read [maxChars]\` | Plain-text page content |
| \`screenshot [outPath]\` | Save a PNG of the viewport and print its path |
| \`console\` | Console logs/errors since the last read (great for dev servers) |
| \`eval <js...>\` | Evaluate JavaScript in the page, print JSON result |
| \`click <x> <y>\` | Click at CSS-pixel viewport coordinates (fallback for canvas) |
| \`type <text...>\` | Type into the focused element |
| \`press <key>\` | Press Enter, Tab, Escape, ArrowDown, ... |
| \`scroll <deltaY>\` | Scroll vertically by pixels (negative = up) |
| \`back\` / \`forward\` | History navigation |
| \`new-tab [url]\` / \`select-tab <id>\` | Tab management |

## Workflow

1. \`navigate <url>\` (or \`tabs\` to reuse an open page)
2. \`page-state\` to see interactive elements with indices
3. \`click-element\` / \`input-text\` / \`select-option\` by index
4. Re-run \`page-state\` after the page changes — indices go stale
5. \`screenshot\` for visual checks; \`console\` when debugging your own app

Set \`FCODE_BROWSER_SESSION\` to a stable name (e.g. the task id) when running
multiple browser tasks in parallel so they don't share one tab selection.
`;
}

// Static CLI: reads runtime.json next to it (rewritten on every server boot), so
// the script itself never goes stale when ports or tokens rotate.
const BROWSER_CLI_SOURCE = `#!/usr/bin/env node
// GENERATED by FCode — cross-provider CLI for the in-app browser. DO NOT EDIT.
import * as fs from "node:fs/promises";
import * as path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const runtime = JSON.parse(await fs.readFile(path.join(here, "runtime.json"), "utf8"));

const [command, ...rest] = process.argv.slice(2);
if (!command) {
  console.error("Usage: browser.mjs <command> [args...] — see SKILL.md");
  process.exit(2);
}

const sessionName = process.env.FCODE_BROWSER_SESSION || "default";

async function call(op, args) {
  const url = new URL(runtime.routePath, runtime.serverUrl);
  if (runtime.token) url.searchParams.set("token", runtime.token);
  let response;
  try {
    response = await fetch(url, {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify({ op, session: sessionName, args }),
    });
  } catch {
    console.error("FCode server is not reachable. Is the FCode desktop app running?");
    process.exit(1);
  }
  const body = await response.json().catch(() => null);
  if (!body || body.ok !== true) {
    console.error((body && body.error) || ("Request failed with status " + response.status));
    process.exit(1);
  }
  return body.result;
}

function requireArg(value, name) {
  if (value === undefined || value === "") {
    console.error("Missing required argument: " + name);
    process.exit(2);
  }
  return value;
}

function toInt(value, name) {
  const parsed = Number.parseInt(requireArg(value, name), 10);
  if (!Number.isFinite(parsed)) {
    console.error("Argument " + name + " must be a number, got: " + value);
    process.exit(2);
  }
  return parsed;
}

function printPage(info) {
  console.log((info.title || "(untitled)") + " — " + info.url + (info.readyState && info.readyState !== "complete" ? " (still loading)" : ""));
}

switch (command) {
  case "tabs": {
    const tabs = await call("tabs", {});
    if (!tabs.length) console.log("No browser tabs are open.");
    for (const tab of tabs) console.log((tab.active ? "* " : "  ") + "[" + tab.id + "] " + tab.title + " — " + tab.url);
    break;
  }
  case "navigate":
    printPage(await call("navigate", { url: requireArg(rest[0], "url") }));
    break;
  case "page-state": {
    const state = await call("page_state", {});
    console.log(state.header + "\\n" + state.content + "\\n" + state.footer);
    break;
  }
  case "click-element":
    console.log((await call("click_element", { index: toInt(rest[0], "index") })).message);
    break;
  case "input-text":
    console.log((await call("input_text", { index: toInt(rest[0], "index"), text: requireArg(rest.slice(1).join(" "), "text") })).message);
    break;
  case "select-option":
    console.log((await call("select_option", { index: toInt(rest[0], "index"), option_text: requireArg(rest.slice(1).join(" "), "option_text") })).message);
    break;
  case "read": {
    const page = await call("read", rest[0] ? { max_chars: toInt(rest[0], "maxChars") } : {});
    console.log(page.title + " — " + page.url + "\\n\\n" + page.text + (page.truncated ? "\\n\\n[truncated — pass a higher maxChars]" : ""));
    break;
  }
  case "screenshot": {
    const shot = await call("screenshot", {});
    const outPath = path.resolve(rest[0] || ("fcode-browser-" + Date.now() + ".png"));
    await fs.writeFile(outPath, Buffer.from(shot.base64Png, "base64"));
    console.log("Saved " + shot.width + "x" + shot.height + " screenshot to " + outPath);
    break;
  }
  case "console": {
    const entries = await call("console", {});
    if (!entries.length) console.log("No console output since the last read.");
    for (const entry of entries) console.log("[" + entry.level + "] " + entry.text);
    break;
  }
  case "eval":
    console.log((await call("eval", { expression: requireArg(rest.join(" "), "js") })).result);
    break;
  case "click":
    await call("click", { x: toInt(rest[0], "x"), y: toInt(rest[1], "y") });
    console.log("Clicked at (" + rest[0] + ", " + rest[1] + ").");
    break;
  case "type":
    await call("type", { text: requireArg(rest.join(" "), "text") });
    console.log("Typed.");
    break;
  case "press":
    await call("press", { key: requireArg(rest[0], "key") });
    console.log("Pressed " + rest[0] + ".");
    break;
  case "scroll":
    await call("scroll", { delta_y: toInt(rest[0], "deltaY") });
    console.log("Scrolled.");
    break;
  case "back":
    printPage(await call("back", {}));
    break;
  case "forward":
    printPage(await call("forward", {}));
    break;
  case "new-tab": {
    const tab = await call("new_tab", {});
    if (rest[0]) printPage(await call("navigate", { url: rest[0] }));
    else console.log("Opened new tab [" + tab.id + "].");
    break;
  }
  case "select-tab":
    await call("select_tab", { tab_id: toInt(rest[0], "tabId") });
    console.log("Selected tab [" + rest[0] + "].");
    break;
  default:
    console.error("Unknown command: " + command + " — see SKILL.md");
    process.exit(2);
}
`;

// Rewrites the skill folder idempotently. runtime.json changes every boot
// (port/token); SKILL.md and browser.mjs only change with FCode versions.
export async function materializeBrowserUseSkill(input: {
  readonly fcodeBaseDir: string;
  readonly serverPort: number;
  readonly authToken: string | undefined;
  readonly env?: NodeJS.ProcessEnv;
}): Promise<string | null> {
  if (!readBrowserUsePipePathFromEnv(input.env ?? process.env)) {
    return null;
  }

  const skillDir = nodePath.join(fcodeSkillsDir(input.fcodeBaseDir), BROWSER_USE_SKILL_NAME);
  await fs.mkdir(skillDir, { recursive: true });

  const runtimeConfig: BrowserUseSkillRuntimeConfig = {
    serverUrl: `http://127.0.0.1:${input.serverPort}`,
    token: input.authToken ?? null,
    routePath: BROWSER_USE_HTTP_ROUTE_PATH,
  };

  await Promise.all([
    fs.writeFile(nodePath.join(skillDir, "SKILL.md"), buildSkillMarkdown(skillDir), "utf8"),
    fs.writeFile(nodePath.join(skillDir, "browser.mjs"), BROWSER_CLI_SOURCE, "utf8"),
    fs.writeFile(
      nodePath.join(skillDir, "runtime.json"),
      `${JSON.stringify(runtimeConfig, null, 2)}\n`,
      "utf8",
    ),
  ]);

  return skillDir;
}
