// FILE: realFileTypeIcons.ts
// Purpose: Map file paths to real, colorful per-extension icon assets (vscode-icons,
//          MIT licensed — see public/file-type-icons/NOTICE.md) for surfaces that want
//          a recognizable brand-style glyph instead of the generic Central icon set.
// Layer: app-level utility
// Depends on: static assets in public/file-type-icons, shared path-resolution walk
//             from file-icons.ts (kept in sync so both icon systems agree on file type).

import { resolveIconByPath } from "../file-icons";

const ICON_ASSET_BASE_PATH = "/file-type-icons";

// Exact basename → icon key. Mirrors the well-known filenames covered in
// file-icons.ts, but keyed to the more specific real-icon set below (e.g. a
// dotenv file gets its own icon instead of the generic "settings" bucket).
const REAL_ICON_KEY_BY_BASENAME: Record<string, string> = {
  "package.json": "npm",
  "package-lock.json": "npm",
  "npm-shrinkwrap.json": "npm",
  ".npmrc": "npm",
  ".npmignore": "npm",
  "yarn.lock": "npm",
  ".yarnrc": "npm",
  ".yarnrc.yml": "npm",
  "pnpm-lock.yaml": "npm",
  "pnpm-workspace.yaml": "npm",
  "bun.lockb": "bun",
  "bun.lock": "bun",
  ".gitignore": "git",
  ".gitattributes": "git",
  ".gitmodules": "git",
  ".gitkeep": "git",
  ".gitconfig": "git",
  "tsconfig.json": "typescript",
  "tsconfig.base.json": "typescript",
  "tsconfig.build.json": "typescript",
  "tsconfig.node.json": "typescript",
  "tsconfig.eslint.json": "typescript",
  "cargo.toml": "rust",
  "cargo.lock": "rust",
  "pyproject.toml": "python",
  "setup.py": "python",
  "readme.md": "markdown",
  license: "license",
  "license.md": "license",
  "license.txt": "license",
  "vercel.json": "vercel",
  dockerfile: "docker",
  "dockerfile.dev": "docker",
  "docker-compose.yml": "docker",
  "docker-compose.yaml": "docker",
  ".env": "dotenv",
  ".env.local": "dotenv",
  ".env.development": "dotenv",
  ".env.production": "dotenv",
  ".env.test": "dotenv",
  ".env.example": "dotenv",
};

// Extension → icon key. Longest extension wins via `resolveIconByPath`'s
// longest-first extension walk (e.g. `.d.ts` before `.ts`).
const REAL_ICON_KEY_BY_EXTENSION: Record<string, string> = {
  html: "html",
  htm: "html",
  css: "css",
  scss: "scss",
  sass: "scss",
  less: "less",
  ts: "typescript",
  mts: "typescript",
  cts: "typescript",
  "d.ts": "typescript",
  tsx: "react",
  jsx: "react",
  js: "javascript",
  mjs: "javascript",
  cjs: "javascript",
  json: "json",
  json5: "json",
  jsonc: "json",
  md: "markdown",
  mdx: "markdown",
  mdc: "markdown",
  markdown: "markdown",
  py: "python",
  pyi: "python",
  pyc: "python",
  pyw: "python",
  rs: "rust",
  go: "go",
  rb: "ruby",
  php: "php",
  phtml: "php",
  java: "java",
  kt: "kotlin",
  kts: "kotlin",
  c: "c",
  h: "c",
  cpp: "cpp",
  cc: "cpp",
  cxx: "cpp",
  hpp: "cpp",
  vue: "vue",
  svelte: "svelte",
  yml: "yaml",
  yaml: "yaml",
  toml: "toml",
  xml: "xml",
  sql: "sql",
  graphql: "graphql",
  gql: "graphql",
  sh: "shell",
  bash: "shell",
  zsh: "shell",
  fish: "shell",
  bat: "shell",
  ps1: "powershell",
  psm1: "powershell",
  psd1: "powershell",
  svg: "svg",
  png: "image",
  jpg: "image",
  jpeg: "image",
  gif: "image",
  webp: "image",
  bmp: "image",
  tiff: "image",
  avif: "image",
  ico: "image",
  pdf: "pdf",
  zip: "zip",
  tar: "zip",
  gz: "zip",
  tgz: "zip",
  rar: "zip",
  "7z": "zip",
  bz2: "zip",
  xz: "zip",
  doc: "word",
  docx: "word",
  xls: "excel",
  xlsx: "excel",
  csv: "excel",
  tsv: "excel",
  mp4: "video",
  m4v: "video",
  mov: "video",
  webm: "video",
  mkv: "video",
  avi: "video",
  mp3: "audio",
  wav: "audio",
  flac: "audio",
  ogg: "audio",
  m4a: "audio",
  aac: "audio",
  ini: "config",
  conf: "config",
  cfg: "config",
  env: "dotenv",
  txt: "text",
  log: "text",
};

// Icon key → static asset filename under public/file-type-icons. A dedicated
// map (rather than using the key as the filename directly) keeps the door open
// for renaming/re-sourcing individual assets without touching the lookup tables.
const REAL_ICON_ASSET_FILE_BY_KEY: Record<string, string> = {
  html: "html.svg",
  css: "css.svg",
  scss: "scss.svg",
  less: "less.svg",
  javascript: "javascript.svg",
  typescript: "typescript.svg",
  react: "react.svg",
  json: "json.svg",
  markdown: "markdown.svg",
  python: "python.svg",
  rust: "rust.svg",
  go: "go.svg",
  ruby: "ruby.svg",
  php: "php.svg",
  java: "java.svg",
  kotlin: "kotlin.svg",
  c: "c.svg",
  cpp: "cpp.svg",
  vue: "vue.svg",
  svelte: "svelte.svg",
  yaml: "yaml.svg",
  toml: "toml.svg",
  xml: "xml.svg",
  sql: "sql.svg",
  graphql: "graphql.svg",
  shell: "shell.svg",
  powershell: "powershell.svg",
  svg: "svg.svg",
  image: "image.svg",
  pdf: "pdf.svg",
  zip: "zip.svg",
  word: "word.svg",
  excel: "excel.svg",
  video: "video.svg",
  audio: "audio.svg",
  config: "config.svg",
  text: "text.svg",
  docker: "docker.svg",
  git: "git.svg",
  npm: "npm.svg",
  bun: "bun.svg",
  dotenv: "dotenv.svg",
  vercel: "vercel.svg",
  license: "license.svg",
};

// Resolves a real, colorful per-file-type icon URL for a path, or `undefined`
// when no dedicated asset exists — callers should fall back to the generic
// Central icon glyph (`FileEntryIcon`) in that case.
export function resolveRealFileTypeIconSrc(pathValue: string): string | undefined {
  const key = resolveIconByPath(pathValue, REAL_ICON_KEY_BY_BASENAME, REAL_ICON_KEY_BY_EXTENSION);
  const file = key ? REAL_ICON_ASSET_FILE_BY_KEY[key] : undefined;
  return file ? `${ICON_ASSET_BASE_PATH}/${file}` : undefined;
}
